"""Bounded legal enumeration of a scenario's strategy options (ADR-0002).

The enumerator turns a race state and a scenario's enumeration parameters into
the finite set of strategy options Jev chooses between. It knows nothing about
lap times: candidates are generated by rule and are never scored, ordered by
quality, or filtered by outcome. The ground-truth simulator is the only component
allowed to rank them (ADR-0002).

Rules
-----
* An option has at most ``enumeration.max_stops`` stops, so at most two
  (``Enumeration`` already validates 0..2).
* The no-stop option ``0STOP`` is always legal and is always included, so the
  candidate set is never empty.
* Pit laps are the positive multiples of ``enumeration.pit_lap_grid`` that lie
  within ``race_state.context.lap..race_state.context.total_laps`` inclusive. A
  stop on the decision lap itself is legal (box this lap); a stop before it is
  not, because that moment has already passed. A grid with no multiple in that
  window therefore contributes no pit laps and only ``0STOP`` is offered.
* Stops within an option are strictly increasing in lap (``StrategyOption``
  enforces this); two-stop options are generated from lap pairs.
* Compounds are drawn only from those available in the race state. The domain
  types carry no explicit availability field, so availability is *derived* as
  the union of the compounds currently in use: the subject car's compound plus
  every rival's compound. A compound may legally be fitted twice.
* Ids come from ``StrategyOption.id`` and are unique by construction.

Ordering
--------
Ordering is structural, never performance-based: fewest stops first, then
lexicographic by the sequence of ``(pit lap, compound enum order)`` pairs. The
rule is deterministic and free of any simulator input.
"""

from __future__ import annotations

from itertools import combinations, product

from pit_strategizer.domain import (
    CandidateSet,
    Compound,
    Enumeration,
    RaceState,
    Stop,
    StrategyOption,
)

__all__ = ["enumerate_candidates"]

# Declaration order of the Compound enum, used only to make ties deterministic.
_COMPOUND_ORDER = {compound: index for index, compound in enumerate(Compound)}


def _available_compounds(race_state: RaceState) -> tuple[Compound, ...]:
    """Compounds in use in this race state, in the Compound enum's order."""
    in_use = {race_state.subject.compound}
    in_use.update(rival.compound for rival in race_state.rivals)
    return tuple(compound for compound in Compound if compound in in_use)


def _ceil_to_grid(value: int, grid: int) -> int:
    """The smallest positive multiple of ``grid`` at or after ``value``."""
    return max(grid, -(-value // grid) * grid)


def _legal_pit_laps(race_state: RaceState, enumeration: Enumeration) -> tuple[int, ...]:
    """Positive multiples of the grid within decision_lap..total_laps inclusive."""
    grid = enumeration.pit_lap_grid
    # A stop on the decision lap is legal; a stop before it is not.
    first_lap = _ceil_to_grid(race_state.context.lap, grid)
    return tuple(range(first_lap, race_state.context.total_laps + 1, grid))


def _sort_key(option: StrategyOption) -> tuple[int, tuple[tuple[int, int], ...]]:
    return (
        option.stop_count,
        tuple((stop.lap, _COMPOUND_ORDER[stop.compound]) for stop in option.stops),
    )


def enumerate_candidates(race_state: RaceState, enumeration: Enumeration) -> CandidateSet:
    """Enumerate every legal strategy option for one decision moment.

    The result is deterministic and depends only on the race state and the
    enumeration parameters; it contains no ranking or simulator output.
    """
    compounds = _available_compounds(race_state)
    pit_laps = _legal_pit_laps(race_state, enumeration)

    options: list[StrategyOption] = [StrategyOption(stops=())]

    if enumeration.max_stops >= 1:
        options.extend(
            StrategyOption(stops=(Stop(lap=lap, compound=compound),))
            for lap in pit_laps
            for compound in compounds
        )

    if enumeration.max_stops >= 2:
        options.extend(
            StrategyOption(
                stops=(
                    Stop(lap=first_lap, compound=first_compound),
                    Stop(lap=second_lap, compound=second_compound),
                )
            )
            for first_lap, second_lap in combinations(pit_laps, 2)
            for first_compound, second_compound in product(compounds, repeat=2)
        )

    options.sort(key=_sort_key)
    return CandidateSet(options=tuple(options))
